[build]
command = "npm i -g npm@latest && npm --version && npm cache clean --force && if [ -f package-lock.json ]; then npm ci --no-audit --prefer-offline; else npm install --no-audit; fi && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
