[build]
command = "npm --version && npm cache clean --force && if [ -f package-lock.json ]; then npm ci --no-audit --prefer-offline; else npm install --no-audit; fi && npm run build"
publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
